### ISSUE TITLE
Crash when editing layout on XinaA15

### ISSUE THREAD

**Issue by socksprox** [ren7995/Atria#15]
Video https://streamable.com/dkkp13

When i try to edit the layout, a respring brings me into safemode

iOS 15.1.1 iPhone 12 Mini XinaA15

**Comment by ren7995** [comment]
Could you please provide a crash log?

**Comment by socksprox** [comment]
> Could you please provide a crash log?

Cr4shed doesn’t work on XinaA15 as i heard, so I unfortunately cannot.

**Comment by ren7995** [comment]
Can you disable all other tweaks with iCleaner to see if this is a tweak conflict related issue? If it isn't, unfortunately I will probably have to wait for Cr4shed to work on Xina, because I can't reproduce this in the iOS simulator

**Comment by ren7995** [comment]
Someone else had the same issue. This only seems to happen on Xina, and completely at random. Most users aren't affected, but inexplicably some are. Palera1n users on the same version do not have this issue.

The crash is related to the setter method for the `_atriaNeedsLayout` not being added properly. Upon examining the output from logos (which generates the code to do this), it looks accurate, and works on every version I've tested, including iOS simulator. I don't see any way of fixing it at this time.

Due to a lack of affected users, inability to reproduce, and so far no leads as to why it happens, I'll be closing the issue. If I find out more in the future, I will try again to address the issue.
