### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by 0cyn** [ren7995/Atria#5]
I spent a few years digging into this and dealing with performance issues on my paid project.

https://github.com/ren7995/Atria/blob/master/Hooks/Layout.xm#L97 

This function right here will get called thousands of times per second while scrolling. While modern phone GPUs are strong enough that this isn't noticeable, you can demonstrate the performance hit on a 1st gen iPhone SE, or demonstrate it tenfold on the iOS simulator. 

I hate reporting an issue without also providing a fix, so I'll try to PR the improvements when I can. 

If you'd like to hit me up, or just want to do it yourself and want pointers, contact me @krit#0443 on discord.

**Comment by ren7995** [comment]
I do already have a rough draft of a caching system in order to improve this, it will just return the cached object unless the layout changes (in which case I will update it)

This should be dealt with soon, but haven't had the time to finalize it due to exams for school. 

I'm familiar with why the whole method is bad, but it's not a property (iirc) so there's no setter for me to hook in order to override it there.
